#!/bin/bash

SCRIPTNAME="$0"
USER_DIR=`eval echo ~$USER`
SCRIPTPATH="$USER_DIR/.teanity-quickstart"
ARGS="$@"
BRANCH="master"

self_update() {
  cwd=`pwd`
  cd $SCRIPTPATH

  ensureGit

  [ -n $(git fetch; git log HEAD.. --oneline) ] && {
      echo "Updating..."
      git pull --force --quiet
      git checkout $BRANCH --quiet
      git pull --force --quiet
      echo "Restarting script..."
      exec "$SCRIPTNAME" "$@"
      cd $cwd

      exit 1
  }
}

ensureGit() {
  command -v git >/dev/null 2>&1 || {
    echo "Error: install git first"
    exit 1
  }
  command -v git fetch >/dev/null 2>&1 || {
    echo "Not a git repository, failed to update"
    exit 1
  }
}

main() {
  defaultFolders="com/skoumal/teanity/example/"
  defaultPackageName=$(echo $defaultFolders | tr "/" ".")
  defaultPackageName=$(sed 's/.\{1\}$//' <<< "$defaultPackageName")

  cwd=$(pwd)
  prefix="app/src/main/java/"

  read -p 'Enter project name: ' projectName
  read -p 'Enter package name: ' packageName

  git clone --recurse-submodules https://github.com/skoumalcz/teanity.git $projectName --quiet && cd $projectName

  rm -rf .git teanity app
  mv quickstart app
  git init >/dev/null

  packageFolders=$(echo $packageName | tr "." "/")

  mkdir -p "$prefix$packageFolders"

  mv -f $prefix$defaultFolders* $prefix$packageFolders
  find . -type d -empty -delete

  if [ "$(uname)" == "Darwin" ]; then
    LC_ALL=C find . -type f -exec sed -i '' "s/${defaultPackageName//./\\.}/${packageName//./\\.}/g" {} +
  else
    LC_ALL=C find . -type f -exec sed -i "s/${defaultPackageName//./\\.}/${packageName//./\\.}/g" {} \;
  fi
}

self_update
main
