#!/bin/bash

SCRIPTNAME="$0"
USER_DIR=`eval echo ~$USER`
SCRIPTPATH="$USER_DIR/.teanity-quickstart"
ARGS="$@"
BRANCH="master"

self_update() {
  echo -ne "Checking for an update...\r"
  cwd=`pwd`
  cd $SCRIPTPATH

  ensureGit

  log=`git fetch --quiet; git log HEAD.. --oneline`

  if [[ "$log" ]]; then
      echo -ne "Updating..."
      git pull --force --quiet
      git checkout $BRANCH --quiet
      git pull --force --quiet
      echo -ne "Restarting script..."
      exec "$SCRIPTNAME" "$@"

      exit 1
  fi

  cd $cwd
  echo -e "Up-to-date ✅\r"
}

ensureGit() {
  command -v git >/dev/null 2>&1 || {
    echo "Error: install git first"
    exit 1
  }
  command -v git fetch >/dev/null 2>&1 || {
    echo "Not a git repository, failed to update"
    exit 1
  }
}

sanitize() {
  _input=$1
  _input=${_input//_/}
  _input=${_input// /_}
  _input=${_input//[^a-zA-Z0-9_]/}
  _input=`echo -n $_input | tr A-Z a-z`
  echo $_input
}

main() {
  defaultFolders="com/skoumal/teanity/app/"
  defaultPackageName=$(echo $defaultFolders | tr "/" ".")
  defaultPackageName=$(sed 's/.\{1\}$//' <<< "$defaultPackageName")

  cwd=$(pwd)
  prefix="/src/main/java/"

  read -p 'Enter project name: ' projectName
  read -p 'Enter package name: ' packageName

  projectName=`sanitize $projectName`

  git clone --recurse-submodules https://github.com/diareuse/teanity-app.git $projectName --quiet && cd $projectName
  git checkout -b one.zero --quiet

  rm -rf .git .github teanity
  git init >/dev/null

  packageFolders=$(echo $packageName | tr "." "/")

  for i in $(ls -d */); do 
    currentFolder=`echo ${i%%/}`
    mkdir -p "$currentFolder$prefix$packageFolders" >/dev/null 2>&1
    mv -f $currentFolder$prefix$defaultFolders* $currentFolder$prefix$packageFolders >/dev/null 2>&1
  done

  find . -type d -empty -delete

  argPackageTarget="${defaultPackageName//./\\.}"
  argPackageReplacement="${packageName//./\\.}"

  if [ "$(uname)" == "Darwin" ]; then
    LC_ALL=C find . -type f -exec sed -i '' "s/$argPackageTarget/$argPackageReplacement/g" {} +
  else
    LC_ALL=C find . -type f -exec sed -i "s/$argPackageTarget/$argPackageReplacement/g" {} \;
  fi
}

self_update
main
